services:
  - type: web
    name: telegram-shop-bot  # این نام به طور خودکار در متغیر RENDER_SERVICE_NAME قرار می‌گیرد
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    port: 8443
    envVars:
      - key: https://telegram-shop-bot-ghak.onrender.com
        value: telegram-shop-bot  # همان نام سرویس