services:
  - type: web
    name: your-bot-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    port: 8443  # باید با پورتی که در کد تعیین کردید مطابقت داشته باشد